# Generated by Django 6.0.1 on 2026-02-05 01:14

from django.db import migrations, models
from datetime import timedelta
class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiveobject',
            name='duration',
            field=models.DurationField(default=timedelta()),
        ),
    ]
