# Generated by Django 6.0.1 on 2026-02-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_productiveobject_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiveobject',
            name='duration',
            field=models.DurationField(default='00:00:00'),
        ),
    ]
